"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type Post={id:number;post_type:string;title:string;description:string;category:string|null;city:string|null;state:string|null;remote:boolean;pay_type:string;pay_amount:number|null;created_at:string};
type LocationSuggestion={city:string;state:string};
function pay(p:Post){if(p.pay_type==="contact"||p.pay_amount==null)return "Pay: discuss details";const n=Number(p.pay_amount).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});return p.pay_type==="hourly"?`${n}/hr`:p.pay_type==="salary"?`${n} salary`:n;}
export default function WorkPage(){
 const [posts,setPosts]=useState<Post[]>([]),[q,setQ]=useState(""),[loc,setLoc]=useState(""),[type,setType]=useState("all"),[mode,setMode]=useState("all"),[loading,setLoading]=useState(true),[suggestions,setSuggestions]=useState<LocationSuggestion[]>([]),[showSuggestions,setShowSuggestions]=useState(false);
 const locationBox=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{fetch("/api/work-posts",{cache:"no-store"}).then(response=>response.json().then(result=>({response,result}))).then(({response,result})=>{if(response.ok)setPosts((Array.isArray(result.posts)?result.posts:[]) as Post[]);setLoading(false);}).catch(()=>setLoading(false));},[]);
 useEffect(()=>{const value=loc.trim();if(value.length<2){setSuggestions([]);return;}const timer=setTimeout(async()=>{try{const response=await fetch(`/api/cities?q=${encodeURIComponent(value)}`);const data=await response.json();setSuggestions(Array.isArray(data?.locations)?data.locations:[]);setShowSuggestions(true);}catch{setSuggestions([]);}},220);return()=>clearTimeout(timer);},[loc]);
 useEffect(()=>{function close(e:MouseEvent){if(locationBox.current&&!locationBox.current.contains(e.target as Node))setShowSuggestions(false);}document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close);},[]);
 const shown=useMemo(()=>posts.filter(p=>{const text=`${p.title} ${p.description} ${p.category||""}`.toLowerCase(),place=`${p.city||""} ${p.state||""}`.toLowerCase(),needle=loc.toLowerCase().replace(","," ").replace(/\s+/g," ").trim();return(type==="all"||p.post_type===type)&&(mode==="all"||(mode==="remote"?p.remote:!p.remote))&&(!q||text.includes(q.toLowerCase()))&&(!needle||place.includes(needle));}),[posts,q,loc,type,mode]);
 const input={padding:"14px 15px",border:"1px solid #d9dce7",borderRadius:12,fontSize:16};
 return <main style={{minHeight:"100vh",background:"#f8f8fb",padding:"36px 18px",fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1000,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"center",flexWrap:"wrap"}}><div><a href="/" style={{color:"#5b4df5",textDecoration:"none",fontWeight:700}}>← YouListify</a><h1 style={{fontSize:"clamp(38px,6vw,58px)",margin:"12px 0 6px",color:"#171b36"}}>Jobs, Gigs & Tasks</h1><p style={{color:"#667085",fontSize:18}}>Find work. Find help. Get it done.</p></div><a href="/post-work" style={{background:"#5b4df5",color:"white",padding:"14px 20px",borderRadius:12,textDecoration:"none",fontWeight:900}}>+ Post Work Free</a></div>
 <div style={{background:"white",padding:18,borderRadius:18,boxShadow:"0 8px 28px rgba(0,0,0,.05)",display:"flex",gap:10,flexWrap:"wrap",margin:"26px 0",alignItems:"flex-start"}}>
  <input style={{...input,flex:"2 1 250px"}} placeholder="What kind of work?" value={q} onChange={e=>setQ(e.target.value)}/>
  <div ref={locationBox} style={{position:"relative",flex:"1 1 210px"}}><input style={{...input,width:"100%",boxSizing:"border-box"}} placeholder="City or state" value={loc} onFocus={()=>suggestions.length&&setShowSuggestions(true)} onChange={e=>{setLoc(e.target.value);setShowSuggestions(true);}} autoComplete="off"/>{showSuggestions&&suggestions.length>0&&<div style={{position:"absolute",zIndex:20,top:"calc(100% + 6px)",left:0,right:0,background:"white",border:"1px solid #e2e4ea",borderRadius:12,boxShadow:"0 10px 28px rgba(0,0,0,.12)",overflow:"hidden"}}>{suggestions.map((s,i)=><button key={`${s.city}-${s.state}-${i}`} type="button" onClick={()=>{setLoc(`${s.city}, ${s.state}`);setShowSuggestions(false);}} style={{display:"block",width:"100%",textAlign:"left",padding:"12px 14px",background:"white",border:0,borderBottom:i<suggestions.length-1?"1px solid #f0f1f4":"none",cursor:"pointer",fontSize:15}}>{s.city}, {s.state}</button>)}</div>}</div>
  <select style={input} value={type} onChange={e=>setType(e.target.value)}><option value="all">All opportunities</option><option value="job">Jobs</option><option value="gig">Gigs</option><option value="task">Tasks</option></select>
  <select style={input} value={mode} onChange={e=>setMode(e.target.value)}><option value="all">Local + Remote</option><option value="local">Local only</option><option value="remote">Remote only</option></select>
 </div>
 {loading?<p>Loading opportunities...</p>:shown.length===0?<div style={{background:"white",borderRadius:20,padding:40,textAlign:"center"}}><h2>No opportunities found</h2><p style={{color:"#667085"}}>Try a different search or be one of the first to post what you need done.</p><a href="/post-work" style={{color:"#5b4df5",fontWeight:800}}>Post work free →</a></div>:<div style={{display:"grid",gap:15}}>{shown.map(p=><a key={p.id} href={`/work/${p.id}`} style={{display:"block",background:"white",border:"1px solid #e8e9f0",borderRadius:18,padding:22,textDecoration:"none",color:"inherit"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><span style={{color:"#5b4df5",fontSize:12,fontWeight:900,textTransform:"uppercase",letterSpacing:1}}>{p.post_type}</span><span style={{color:"#667085",fontWeight:700}}>{pay(p)}</span></div><h2 style={{margin:"9px 0",color:"#171b36"}}>{p.title}</h2><p style={{color:"#667085",margin:"0 0 12px",lineHeight:1.5}}>{p.description.length>180?p.description.slice(0,180)+"…":p.description}</p><strong style={{color:"#454b60"}}>{p.remote?"Remote":([p.city,p.state].filter(Boolean).join(", ")||"Location flexible")}{p.category?` · ${p.category}`:""}</strong></a>)}</div>}</div></main>;
}
