"use client";

import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { useParams } from "next/navigation";

export default function ProviderProfile() {
const params = useParams();
const slug = params.slug as string;
const [provider, setProvider] = useState<any>(null);
const [loading, setLoading] = useState(true);
const [currentUserId, setCurrentUserId] = useState<string | null>(null);
const [linkCopied, setLinkCopied] = useState(false);
const [contactOpen,setContactOpen]=useState(false);
const [contactName,setContactName]=useState("");
const [contactEmail,setContactEmail]=useState("");
const [contactMessage,setContactMessage]=useState("");
const [sending,setSending]=useState(false);
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

useEffect(()=>{async function getCurrentUser(){const {data}=await supabase.auth.getUser();setCurrentUserId(data.user?.id??null);}getCurrentUser();},[]);
useEffect(()=>{async function loadProvider(){const id=slug.split("-").pop();const {data,error}=await supabase.from("Providers").select(`*,provider_services (services (name))`).eq("id",id).single();if(!error&&data){setProvider({...data,specialties:Array.from(new Set(data.provider_services?.map((ps:any)=>ps.services?.name).filter(Boolean)||[]))});}setLoading(false);}if(slug)loadProvider();},[slug]);
if(loading)return <main style={{padding:"40px"}}>Loading profile...</main>;
if(!provider)return <main style={{padding:"40px"}}>Provider not found.</main>;
const displayName=provider.business_name||(provider.name_display==="first"?provider.name:provider.name_display==="initial"?`${provider.name} ${provider.last_name?.charAt(0)||""}.`:`${provider.name} ${provider.last_name||""}`.trim());
const serviceModeLabel=provider.service_mode==="local"?"Local / In-person":provider.service_mode==="remote"?"Remote / Online":provider.service_mode==="both"?"Local + Remote":"";
const deliveryDetails=[provider.customer_comes_to_me?"Customer comes to me":null,provider.mobile_service?"Mobile / I travel to customers":null].filter(Boolean) as string[];
const pricingMethods=Array.isArray(provider.pricing_methods)?provider.pricing_methods:[];
const hasPricing=(label:string,legacy:string)=>pricingMethods.includes(label)||pricingMethods.includes(legacy);
async function copyProfileLink(){const url=window.location.href;try{await navigator.clipboard.writeText(url);setLinkCopied(true);window.setTimeout(()=>setLinkCopied(false),2200);}catch{const input=document.createElement("input");input.value=url;document.body.appendChild(input);input.select();document.execCommand("copy");document.body.removeChild(input);setLinkCopied(true);window.setTimeout(()=>setLinkCopied(false),2200);}}
async function sendProviderMessage(){if(!contactName.trim()||!contactEmail.trim()||!contactMessage.trim()){alert("Please complete your name, email, and message.");return;}const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(!emailPattern.test(contactEmail.trim())){alert("Please enter a valid email address.");return;}setSending(true);const {error}=await supabase.functions.invoke("send-provider-message",{body:{providerId:provider.id,customerName:contactName.trim(),customerEmail:contactEmail.trim(),message:contactMessage.trim()}});setSending(false);if(error){console.error(error);alert("Your message could not be sent. Please try again.");return;}alert("Message sent!");setContactName("");setContactEmail("");setContactMessage("");setContactOpen(false);}
return <main style={{minHeight:"100vh",background:"#f6f7fb",padding:"40px 20px"}}><div style={{maxWidth:"760px",margin:"0 auto"}}>{currentUserId&&provider.user_id===currentUserId?<a href="/dashboard/edit" style={{color:"#4f46e5",textDecoration:"none",fontWeight:"600"}}>← Back to Edit Listing</a>:<a href="/" style={{color:"#4f46e5",textDecoration:"none",fontWeight:"600"}}>← Back to YouListify</a>}<div style={{background:"white",borderRadius:"28px",padding:"32px",marginTop:"24px",boxShadow:"0 18px 50px rgba(0,0,0,0.08)"}}><div style={{display:"flex",alignItems:"center",gap:"18px",marginBottom:"22px"}}><div className="avatar" style={{width:"82px",height:"82px",borderRadius:"24px",background:"linear-gradient(135deg, #5b5bf7, #8b5cf6)",color:"white",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"28px",fontWeight:"700",flexShrink:0,backgroundImage:provider.profile_photo?`url(${provider.profile_photo})`:undefined,backgroundSize:"contain",backgroundPosition:"center",backgroundRepeat:"no-repeat"}}>{provider.profile_photo?"":displayName?.charAt(0).toUpperCase()}</div><div><h1 style={{margin:0,fontSize:"36px",lineHeight:1.1}}>{displayName}</h1><p style={{margin:"8px 0 0",color:"#6b7280"}}>{provider.city}{provider.state?`, ${provider.state}`:""}</p>{serviceModeLabel&&<div style={{marginTop:"10px",display:"inline-block",background:"#f5f3ff",color:"#4f46e5",borderRadius:"999px",padding:"6px 12px",fontWeight:"600"}}>📍 {serviceModeLabel}</div>}{provider.available_now&&<div style={{marginTop:"10px",marginLeft:serviceModeLabel?"8px":"0",display:"inline-block",background:"#ecfdf3",color:"#15803d",borderRadius:"999px",padding:"6px 12px",fontWeight:"600"}}>● Available now</div>}{deliveryDetails.length>0&&<div style={{display:"flex",flexWrap:"wrap",gap:"8px",marginTop:"10px"}}>{deliveryDetails.map(detail=><span key={detail} style={{display:"inline-block",background:"#f8fafc",color:"#475569",border:"1px solid #e2e8f0",borderRadius:"999px",padding:"6px 10px",fontWeight:"600",fontSize:"14px"}}>{detail}</span>)}</div>}</div></div>
{provider.bio&&<div style={{marginTop:"24px"}}><h3 style={{marginBottom:"8px"}}>About</h3><p style={{color:"#4b5563",lineHeight:1.7,margin:0}}>{provider.bio}</p></div>}
{provider.specialties?.length>0&&<div style={{marginTop:"26px"}}><h3 style={{marginBottom:"10px"}}>Services</h3><div style={{display:"flex",flexWrap:"wrap",gap:"8px"}}>{provider.specialties.map((service:string)=><span key={service} style={{background:"#f3f4f6",borderRadius:"999px",padding:"8px 12px",fontSize:"14px"}}>{service}</span>)}</div></div>}
{pricingMethods.length>0&&<div style={{marginTop:"26px"}}><h3 style={{marginBottom:"10px"}}>Pricing</h3><div style={{display:"flex",flexWrap:"wrap",gap:"10px"}}>{hasPricing("Hourly rate","hourly")&&<span style={{background:"#f5f3ff",padding:"9px 12px",borderRadius:"10px",fontWeight:"600"}}>{provider.starting_price!=null?`$${provider.starting_price}/hour`:"Hourly rate"}</span>}{hasPricing("Flat rate","flat")&&<span style={{background:"#f5f3ff",padding:"9px 12px",borderRadius:"10px",fontWeight:"600"}}>{provider.flat_price!=null?`Flat rate: $${provider.flat_price}`:"Flat rate"}</span>}{hasPricing("Contact for pricing","contact")&&<span style={{background:"#f5f3ff",padding:"9px 12px",borderRadius:"10px",fontWeight:"600"}}>Contact for pricing</span>}</div></div>}
<div style={{display:"flex",flexWrap:"wrap",gap:"10px",justifyContent:"center",marginTop:"30px"}}>{provider.contact_call&&provider.phone&&<a href={`tel:${provider.phone}`} style={{background:"#4f46e5",color:"white",padding:"12px 18px",borderRadius:"10px",textDecoration:"none",fontWeight:"600"}}>☎ Call {provider.phone}</a>}{provider.contact_text&&provider.phone&&<a href={`sms:${provider.phone}`} style={{background:"#4f46e5",color:"white",padding:"12px 18px",borderRadius:"10px",textDecoration:"none",fontWeight:"600"}}>💬 Text</a>}{provider.contact_email&&provider.email&&<a href={`mailto:${provider.email}`} style={{background:"#4f46e5",color:"white",padding:"12px 18px",borderRadius:"10px",textDecoration:"none",fontWeight:"600"}}>✉ Email</a>}{provider.contact_youlistify&&<button type="button" onClick={()=>setContactOpen(true)} style={{background:"#4f46e5",color:"white",padding:"12px 18px",borderRadius:"10px",border:"none",fontWeight:"600",cursor:"pointer"}}>✉ Contact through YouListify</button>}<button type="button" onClick={copyProfileLink} style={{background:"#f5f3ff",color:"#4f46e5",padding:"12px 18px",borderRadius:"10px",border:"1px solid #ddd6fe",fontWeight:"700",cursor:"pointer"}}>{linkCopied?"✓ Link Copied":"🔗 Copy Profile Link"}</button><button type="button" onClick={async()=>{const url=window.location.href;if(navigator.share){await navigator.share({title:`${displayName} on YouListify`,url});}else{await copyProfileLink();}}} style={{background:"#4f46e5",color:"white",padding:"12px 18px",borderRadius:"10px",border:"none",fontWeight:"600",cursor:"pointer"}}>↗ Share profile</button></div>
{provider.gallery_photos?.length>0&&<div style={{marginTop:"26px"}}><h3 style={{marginBottom:"12px"}}>Photos</h3><div style={{display:"grid",gridTemplateColumns:"repeat(3, 1fr)",gap:"10px"}}>{provider.gallery_photos.map((photo:string,index:number)=><img key={index} src={photo} alt={`${displayName} photo ${index+1}`} style={{width:"100%",height:"auto",maxHeight:"360px",objectFit:"contain",borderRadius:"12px"}}/>)}</div></div>}</div></div>{contactOpen&&<div onClick={()=>setContactOpen(false)} style={{position:"fixed",inset:0,background:"rgba(15,23,42,.55)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px",zIndex:1000}}><div onClick={e=>e.stopPropagation()} style={{width:"100%",maxWidth:"520px",background:"white",borderRadius:"24px",padding:"28px",boxShadow:"0 20px 60px rgba(0,0,0,.2)",position:"relative"}}><button type="button" onClick={()=>setContactOpen(false)} aria-label="Close" style={{position:"absolute",right:"18px",top:"14px",border:"none",background:"transparent",fontSize:"28px",cursor:"pointer",color:"#6b7280"}}>×</button><h2 style={{margin:"0 36px 8px 0",fontSize:"28px"}}>Contact {displayName}</h2><p style={{color:"#667085",marginTop:0}}>Send a private message through YouListify.</p><input type="text" placeholder="Your name" value={contactName} onChange={e=>setContactName(e.target.value)} style={{width:"100%",boxSizing:"border-box",padding:"13px",border:"1px solid #d1d5db",borderRadius:"10px",fontSize:"16px",marginBottom:"12px"}}/><input type="email" placeholder="Your email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)} style={{width:"100%",boxSizing:"border-box",padding:"13px",border:"1px solid #d1d5db",borderRadius:"10px",fontSize:"16px",marginBottom:"12px"}}/><textarea placeholder="Your message" value={contactMessage} onChange={e=>setContactMessage(e.target.value)} rows={5} style={{width:"100%",boxSizing:"border-box",padding:"13px",border:"1px solid #d1d5db",borderRadius:"10px",fontSize:"16px",marginBottom:"14px",resize:"vertical"}}/><button type="button" disabled={sending} onClick={sendProviderMessage} style={{width:"100%",background:"#4f46e5",color:"white",padding:"13px 18px",borderRadius:"10px",border:"none",fontWeight:"700",fontSize:"16px",cursor:"pointer"}}>{sending?"Sending...":"Send message"}</button></div></div>}</main>;
}
