"use client";
import {useEffect,useState} from "react";
import { createClient } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
export default function WorkDetail({params}:{params:Promise<{id:string}>}){
 const [p,setP]=useState<any>(null),[loading,setLoading]=useState(true),[emailOpen,setEmailOpen]=useState(false),[copied,setCopied]=useState(false),[signedIn,setSignedIn]=useState(false);
 const [contactOpen,setContactOpen]=useState(false),[contactName,setContactName]=useState(""),[contactEmail,setContactEmail]=useState(""),[contactMessage,setContactMessage]=useState(""),[sending,setSending]=useState(false),[contactStatus,setContactStatus]=useState(""),[contactError,setContactError]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSignedIn(!!data.session?.user));params.then(async({id})=>{try{const response=await fetch(`/api/work-posts?id=${encodeURIComponent(id)}`,{cache:"no-store"});const result=await response.json();if(response.ok)setP(result.post);}finally{setLoading(false);}});},[params]);
 if(loading)return <main style={{padding:40}}>Loading...</main>;if(!p)return <main style={{padding:40}}><h1>Opportunity not found</h1><a href="/work">Back to Jobs, Gigs & Tasks</a></main>;
 const locationMode=p.location_mode||(p.remote?"remote":"local");const localPlace=[p.city,p.state].filter(Boolean).join(", ");const place=locationMode==="remote"?"Remote":locationMode==="both"&&localPlace?`${localPlace} + Local + Remote`:(localPlace||"Location flexible");const currentUrl=typeof window==="undefined"?"":window.location.href;const reportHref=`/report?type=post&title=${encodeURIComponent(p.title)}&url=${encodeURIComponent(currentUrl)}&id=${encodeURIComponent(String(p.id||""))}`;const amount=p.pay_amount?Number(p.pay_amount).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}):"";const pay=p.pay_type==="contact"?"Pay: discuss details":p.pay_type==="hourly"?`${amount}/hr`:p.pay_type==="salary"?`${amount} salary`:amount;
 async function copyEmail(){if(!p.contact_email_address)return;try{await navigator.clipboard.writeText(p.contact_email_address);}catch{const input=document.createElement("input");input.value=p.contact_email_address;document.body.appendChild(input);input.select();document.execCommand("copy");document.body.removeChild(input);}setCopied(true);setTimeout(()=>setCopied(false),2000);}
 async function sendYouListifyMessage(){setContactError("");if(!contactName.trim()||!contactEmail.trim()||!contactMessage.trim()){setContactError("Please complete your name, email, and message.");return;}const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(!emailPattern.test(contactEmail.trim())){setContactError("Please enter a valid email address.");return;}setSending(true);try{const response=await fetch("/api/work-message",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({postId:p.id,senderName:contactName.trim(),senderEmail:contactEmail.trim(),message:contactMessage.trim()})});let result:any={};try{result=await response.json();}catch{}setSending(false);if(!response.ok){setContactError(`Your message could not be sent yet. ${result.error||"Please try again."}${result.code?` (Code ${result.code})`:""}`);return;}setContactStatus("Message sent!");setContactName("");setContactEmail("");setContactMessage("");}catch{setSending(false);setContactError("Your message could not be sent yet. Please try again.");}}
 return <main style={{minHeight:"100vh",background:"#f8f8fb",padding:"40px 18px",fontFamily:"Arial,sans-serif"}}><article style={{maxWidth:800,margin:"0 auto",background:"white",padding:"clamp(26px,5vw,46px)",borderRadius:24,boxShadow:"0 10px 35px rgba(0,0,0,.07)"}}><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"center"}}><a href="/work" style={{color:"#5b4df5",fontWeight:800,textDecoration:"none"}}>← Jobs, Gigs & Tasks</a>{signedIn&&<a href="/dashboard" style={{color:"#5b4df5",fontWeight:900,textDecoration:"none",border:"1px solid #d8d2ff",background:"#f7f5ff",borderRadius:999,padding:"9px 12px"}}>← Back to Dashboard</a>}</div><div style={{marginTop:24,color:"#5b4df5",fontWeight:900,textTransform:"uppercase",letterSpacing:1}}>{p.post_type}</div><h1 style={{fontSize:"clamp(34px,6vw,50px)",lineHeight:1.08,color:"#171b36",margin:"10px 0"}}>{p.title}</h1><div style={{display:"flex",gap:14,flexWrap:"wrap",color:"#667085",fontWeight:700}}><span>📍 {place}</span>{p.category&&<span>✦ {p.category}</span>}<span>💵 {pay}</span></div><div style={{height:1,background:"#ececf2",margin:"28px 0"}}/><h2>What they need</h2><p style={{whiteSpace:"pre-wrap",fontSize:17,lineHeight:1.7,color:"#454b60"}}>{p.description}</p><div style={{height:1,background:"#ececf2",margin:"28px 0"}}/><h2>Respond</h2><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:16}}>{p.contact_call&&p.contact_phone&&<a href={`tel:${p.contact_phone}`} style={btn}>Call</a>}{p.contact_text&&p.contact_phone&&<a href={`sms:${p.contact_phone}`} style={btn}>Text</a>}{p.contact_email&&p.contact_email_address&&<button type="button" onClick={()=>setEmailOpen(true)} style={btn}>Email</button>}{p.application_url&&<a href={p.application_url.startsWith("http")?p.application_url:`https://${p.application_url}`} target="_blank" rel="noreferrer" style={btn}>Apply / Website</a>}{p.contact_youlistify&&<button type="button" onClick={()=>{setContactStatus("");setContactError("");setContactOpen(true);}} style={{...btn,background:"#5b4df5",color:"white",cursor:"pointer"}}>Contact through YouListify</button>}</div><p style={{color:"#667085",fontSize:14,lineHeight:1.55,margin:"16px 0 0"}}>YouListify helps people connect. Please use your own judgment before accepting work, meeting, paying, or sharing personal information.</p><p style={{margin:"10px 0 0"}}><a href={reportHref} style={{color:"#667085",fontSize:14,fontWeight:800}}>Report post</a></p></article>
 {emailOpen&&<div onClick={()=>setEmailOpen(false)} style={overlay}><div onClick={e=>e.stopPropagation()} style={modal}><h2 style={{marginTop:0}}>Email about this post</h2><p style={{color:"#667085",lineHeight:1.6}}>If your browser does not open your mail app automatically, copy the email address below.</p><div style={{padding:"13px 14px",background:"#f8f8fb",borderRadius:10,wordBreak:"break-all",fontWeight:700,marginBottom:14}}>{p.contact_email_address}</div><div style={{display:"grid",gap:10}}><a href={`mailto:${p.contact_email_address}?subject=${encodeURIComponent("YouListify: "+p.title)}`} style={{...btn,background:"#5b4df5",color:"white",textAlign:"center"}}>Open email app</a><button type="button" onClick={copyEmail} style={{...btn,cursor:"pointer"}}>{copied?"✓ Email copied":"Copy email address"}</button><button type="button" onClick={()=>setEmailOpen(false)} style={{...btn,cursor:"pointer"}}>Close</button></div></div></div>}
 {contactOpen&&<div onClick={()=>setContactOpen(false)} style={overlay}><div onClick={e=>e.stopPropagation()} style={modal}><button type="button" onClick={()=>setContactOpen(false)} aria-label="Close" style={{position:"absolute",right:18,top:12,border:0,background:"transparent",fontSize:28,cursor:"pointer",color:"#667085"}}>×</button>{contactStatus?<div style={{textAlign:"center",padding:"18px 4px 4px"}}><h2 style={{margin:"0 0 16px",color:"#15803d",fontSize:28}}>Message sent!</h2><p style={{color:"#101828",lineHeight:1.5,margin:"0 0 26px",fontWeight:700}}>Your message was sent through YouListify.</p><button type="button" onClick={()=>setContactOpen(false)} style={{...btn,background:"#ff2b7a",color:"white",borderColor:"#ff2b7a",cursor:"pointer",fontSize:16}}>Done</button></div>:<><h2 style={{margin:"0 36px 8px 0"}}>Contact about this post</h2><p style={{color:"#667085",lineHeight:1.6,marginTop:0}}>Send a private message through YouListify. The poster can read it from their dashboard.</p><p style={{color:"#667085",fontSize:14,lineHeight:1.55,marginTop:0}}>YouListify helps people connect. Please use your own judgment before accepting work, meeting, paying, or sharing personal information.</p><input style={field} placeholder="Your name" value={contactName} onChange={e=>setContactName(e.target.value)}/><input style={field} type="email" placeholder="Your email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)}/><textarea style={{...field,minHeight:130,resize:"vertical"}} placeholder="Your message" value={contactMessage} onChange={e=>setContactMessage(e.target.value)}/>{contactError&&<p style={{color:"#b42318",fontWeight:800,lineHeight:1.4,margin:"0 0 12px"}}>{contactError}</p>}<button type="button" disabled={sending} onClick={sendYouListifyMessage} style={{...btn,width:"100%",background:"#5b4df5",color:"white",cursor:"pointer",fontSize:16}}>{sending?"Sending...":"Send through YouListify"}</button></>}</div></div>}
 </main>;
}
const btn={padding:"13px 18px",borderRadius:11,border:"1px solid #d9dce7",textDecoration:"none",fontWeight:800,color:"#4f46e5",background:"white"};
const overlay={position:"fixed" as const,inset:0,background:"rgba(15,23,42,.55)",display:"flex",alignItems:"center",justifyContent:"center",padding:20,zIndex:1000};
const modal={width:"100%",maxWidth:480,background:"white",borderRadius:22,padding:26,boxShadow:"0 20px 60px rgba(0,0,0,.2)",position:"relative" as const};
const field={width:"100%",boxSizing:"border-box" as const,padding:13,border:"1px solid #d1d5db",borderRadius:10,fontSize:16,marginBottom:12};
