"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
export default function WorkDetail({params}:{params:Promise<{id:string}>}){
 const [p,setP]=useState<any>(null),[loading,setLoading]=useState(true),[emailOpen,setEmailOpen]=useState(false),[copied,setCopied]=useState(false);
 const [contactOpen,setContactOpen]=useState(false),[contactName,setContactName]=useState(""),[contactEmail,setContactEmail]=useState(""),[contactMessage,setContactMessage]=useState(""),[sending,setSending]=useState(false);
 useEffect(()=>{params.then(({id})=>supabase.from("work_posts").select("*").eq("id",id).single().then(({data})=>{setP(data);setLoading(false);}));},[params]);
 if(loading)return <main style={{padding:40}}>Loading...</main>;if(!p)return <main style={{padding:40}}><h1>Opportunity not found</h1><a href="/work">Back to Jobs, Gigs & Tasks</a></main>;
 const place=p.remote?"Remote":([p.city,p.state].filter(Boolean).join(", ")||"Location flexible");const amount=p.pay_amount?Number(p.pay_amount).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}):"";const pay=p.pay_type==="contact"?"Pay: discuss details":p.pay_type==="hourly"?`${amount}/hr`:p.pay_type==="salary"?`${amount} salary`:amount;
 async function copyEmail(){if(!p.contact_email_address)return;try{await navigator.clipboard.writeText(p.contact_email_address);}catch{const input=document.createElement("input");input.value=p.contact_email_address;document.body.appendChild(input);input.select();document.execCommand("copy");document.body.removeChild(input);}setCopied(true);setTimeout(()=>setCopied(false),2000);}
 async function sendYouListifyMessage(){if(!contactName.trim()||!contactEmail.trim()||!contactMessage.trim()){alert("Please complete your name, email, and message.");return;}const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(!emailPattern.test(contactEmail.trim())){alert("Please enter a valid email address.");return;}setSending(true);const {error}=await supabase.from("work_post_messages").insert({work_post_id:p.id,sender_name:contactName.trim(),sender_email:contactEmail.trim(),message:contactMessage.trim()});setSending(false);if(error){console.error(error);alert("Your message could not be sent yet. Please try again.");return;}alert("Message sent through YouListify!");setContactName("");setContactEmail("");setContactMessage("");setContactOpen(false);}
 return <main style={{minHeight:"100vh",background:"#f8f8fb",padding:"40px 18px",fontFamily:"Arial,sans-serif"}}><article style={{maxWidth:800,margin:"0 auto",background:"white",padding:"clamp(26px,5vw,46px)",borderRadius:24,boxShadow:"0 10px 35px rgba(0,0,0,.07)"}}><a href="/work" style={{color:"#5b4df5",fontWeight:800,textDecoration:"none"}}>← Jobs, Gigs & Tasks</a><div style={{marginTop:24,color:"#5b4df5",fontWeight:900,textTransform:"uppercase",letterSpacing:1}}>{p.post_type}</div><h1 style={{fontSize:"clamp(34px,6vw,50px)",lineHeight:1.08,color:"#171b36",margin:"10px 0"}}>{p.title}</h1><div style={{display:"flex",gap:14,flexWrap:"wrap",color:"#667085",fontWeight:700}}><span>📍 {place}</span>{p.category&&<span>✦ {p.category}</span>}<span>💵 {pay}</span></div><div style={{height:1,background:"#ececf2",margin:"28px 0"}}/><h2>What they need</h2><p style={{whiteSpace:"pre-wrap",fontSize:17,lineHeight:1.7,color:"#454b60"}}>{p.description}</p><div style={{height:1,background:"#ececf2",margin:"28px 0"}}/><h2>Respond</h2><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:16}}>{p.contact_call&&p.contact_phone&&<a href={`tel:${p.contact_phone}`} style={btn}>Call</a>}{p.contact_text&&p.contact_phone&&<a href={`sms:${p.contact_phone}`} style={btn}>Text</a>}{p.contact_email&&p.contact_email_address&&<button type="button" onClick={()=>setEmailOpen(true)} style={btn}>Email</button>}{p.application_url&&<a href={p.application_url.startsWith("http")?p.application_url:`https://${p.application_url}`} target="_blank" rel="noreferrer" style={btn}>Apply / Website</a>}{p.contact_youlistify&&<button type="button" onClick={()=>setContactOpen(true)} style={{...btn,background:"#5b4df5",color:"white",cursor:"pointer"}}>Contact through YouListify</button>}</div></article>
 {emailOpen&&<div onClick={()=>setEmailOpen(false)} style={overlay}><div onClick={e=>e.stopPropagation()} style={modal}><h2 style={{marginTop:0}}>Email about this post</h2><p style={{color:"#667085",lineHeight:1.6}}>If your browser does not open your mail app automatically, copy the email address below.</p><div style={{padding:"13px 14px",background:"#f8f8fb",borderRadius:10,wordBreak:"break-all",fontWeight:700,marginBottom:14}}>{p.contact_email_address}</div><div style={{display:"grid",gap:10}}><a href={`mailto:${p.contact_email_address}?subject=${encodeURIComponent("YouListify: "+p.title)}`} style={{...btn,background:"#5b4df5",color:"white",textAlign:"center"}}>Open email app</a><button type="button" onClick={copyEmail} style={{...btn,cursor:"pointer"}}>{copied?"✓ Email copied":"Copy email address"}</button><button type="button" onClick={()=>setEmailOpen(false)} style={{...btn,cursor:"pointer"}}>Close</button></div></div></div>}
 {contactOpen&&<div onClick={()=>setContactOpen(false)} style={overlay}><div onClick={e=>e.stopPropagation()} style={modal}><button type="button" onClick={()=>setContactOpen(false)} aria-label="Close" style={{position:"absolute",right:18,top:12,border:0,background:"transparent",fontSize:28,cursor:"pointer",color:"#667085"}}>×</button><h2 style={{margin:"0 36px 8px 0"}}>Contact about this post</h2><p style={{color:"#667085",lineHeight:1.6,marginTop:0}}>Send a private message through YouListify. The poster can read it from their dashboard.</p><input style={field} placeholder="Your name" value={contactName} onChange={e=>setContactName(e.target.value)}/><input style={field} type="email" placeholder="Your email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)}/><textarea style={{...field,minHeight:130,resize:"vertical"}} placeholder="Your message" value={contactMessage} onChange={e=>setContactMessage(e.target.value)}/><button type="button" disabled={sending} onClick={sendYouListifyMessage} style={{...btn,width:"100%",background:"#5b4df5",color:"white",cursor:"pointer",fontSize:16}}>{sending?"Sending...":"Send through YouListify"}</button></div></div>}
 </main>;
}
const btn={padding:"13px 18px",borderRadius:11,border:"1px solid #d9dce7",textDecoration:"none",fontWeight:800,color:"#4f46e5",background:"white"};
const overlay={position:"fixed" as const,inset:0,background:"rgba(15,23,42,.55)",display:"flex",alignItems:"center",justifyContent:"center",padding:20,zIndex:1000};
const modal={width:"100%",maxWidth:480,background:"white",borderRadius:22,padding:26,boxShadow:"0 20px 60px rgba(0,0,0,.2)",position:"relative" as const};
const field={width:"100%",boxSizing:"border-box" as const,padding:13,border:"1px solid #d1d5db",borderRadius:10,fontSize:16,marginBottom:12};
