import type { Metadata } from "next";
import LegalReturnLink from "../LegalReturnLink";

export const metadata: Metadata = { title: "Terms of Use | YouListify", description: "Terms for using the YouListify marketplace." };

export default function TermsPage(){return <main style={{minHeight:"100vh",background:"#fbfcff",color:"#101a38",fontFamily:'Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif'}}>
<header style={{height:82,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 5.3vw",background:"white",borderBottom:"1px solid #eef0f5"}}><a href="/" style={{display:"flex",alignItems:"center",gap:11,textDecoration:"none",color:"#101a38",fontSize:22,fontWeight:850}}><span style={{display:"grid",placeItems:"center",width:40,height:40,borderRadius:13,background:"#5b4df5",color:"white",fontWeight:900}}>Y</span>YouListify</a><div style={{display:"flex",alignItems:"center",gap:18}}><LegalReturnLink/><a href="/" style={{color:"#5b4df5",textDecoration:"none",fontWeight:750}}>Back to home</a></div></header>
<article style={{maxWidth:900,margin:"0 auto",padding:"64px 22px 80px",lineHeight:1.72}}><div style={{color:"#5b4df5",fontSize:12,fontWeight:900,letterSpacing:'.12em',textTransform:"uppercase"}}>Legal</div><h1 style={{fontSize:"clamp(38px,6vw,64px)",letterSpacing:"-.04em",margin:"10px 0"}}>Terms of Use</h1><p style={{color:"#667085",marginBottom:36}}>Effective August 24, 2026</p>
<p>These Terms govern your use of YouListify. By using the service, you agree to these Terms.</p>
<h2>What YouListify is</h2><p>YouListify is a marketplace that helps people discover and contact independent service providers. YouListify is not the employer, agent, contractor, partner, or representative of providers or customers and is not a party to agreements they make with one another.</p>
<h2>Accounts and listings</h2><p>You are responsible for information submitted through your account and for keeping account credentials secure. Listing information must be accurate, lawful, and not misleading. You must have the right to publish any photos, text, business information, or other content you submit.</p>
<h2>Provider responsibility</h2><p>Providers are responsible for determining and maintaining any licenses, permits, insurance, certifications, registrations, qualifications, taxes, and legal requirements applicable to their services. Unless YouListify expressly states otherwise, a listing does not mean that YouListify has background checked, licensed, insured, certified, endorsed, or independently verified a provider.</p>
<h2>Customer responsibility</h2><p>Customers are responsible for evaluating providers and deciding whether a provider is appropriate for a particular job. Customers should independently verify credentials, references, insurance, licenses, pricing, scope, and other information when relevant.</p>
<h2>Direct transactions</h2><p>Providers and customers communicate and make arrangements directly. They are responsible for pricing, payment, scheduling, performance, cancellations, disputes, taxes, property access, and other terms of their engagement unless a future YouListify feature expressly provides otherwise.</p>
<h2>Acceptable use</h2><p>You may not use YouListify for fraud, harassment, impersonation, unlawful discrimination, spam, deceptive listings, illegal services, infringement of another person's rights, attempts to compromise platform security, or other unlawful or harmful activity. We may remove content or restrict accounts when reasonably necessary to protect the service or its users.</p>
<h2>Founding Provider offer and future fees</h2><p>Promotional or free access may be offered for a stated period. Any future paid membership price and applicable terms will be disclosed before a charge is made. Promotional terms may apply only to eligible accounts and may change for new participants.</p>
<h2>No guarantee</h2><p>YouListify does not guarantee that a provider will receive work, that a customer will find a suitable provider, or that any transaction or engagement will meet a user's expectations. Availability indicators and profile information are supplied or controlled by providers and may change.</p>
<h2>Limitation and disputes</h2><p>To the fullest extent permitted by applicable law, YouListify is not responsible for the acts, omissions, services, statements, payments, property damage, personal injury, disputes, or transactions between users. Nothing in these Terms excludes rights or remedies that cannot lawfully be excluded.</p>
<h2>Changes</h2><p>We may update these Terms as YouListify develops. Continued use after updated Terms become effective constitutes acceptance of the revised Terms to the extent permitted by law.</p>
<div style={{marginTop:36,padding:22,border:"1px solid #e7eaf0",borderRadius:18,background:"white"}}><strong>Need help?</strong><br/><a href="/support" style={{color:"#5b4df5",fontWeight:800}}>Visit Contact &amp; Support</a> · <a href="/safety" style={{color:"#5b4df5",fontWeight:800}}>Safety &amp; Resources</a></div></article></main>}
