"use client";

import "../../list-service/mobile.css";
import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

const STATES = [
["AL","Alabama"],["AK","Alaska"],["AZ","Arizona"],["AR","Arkansas"],["CA","California"],["CO","Colorado"],["CT","Connecticut"],["DE","Delaware"],["FL","Florida"],["GA","Georgia"],["HI","Hawaii"],["ID","Idaho"],["IL","Illinois"],["IN","Indiana"],["IA","Iowa"],["KS","Kansas"],["KY","Kentucky"],["LA","Louisiana"],["ME","Maine"],["MD","Maryland"],["MA","Massachusetts"],["MI","Michigan"],["MN","Minnesota"],["MS","Mississippi"],["MO","Missouri"],["MT","Montana"],["NE","Nebraska"],["NV","Nevada"],["NH","New Hampshire"],["NJ","New Jersey"],["NM","New Mexico"],["NY","New York"],["NC","North Carolina"],["ND","North Dakota"],["OH","Ohio"],["OK","Oklahoma"],["OR","Oregon"],["PA","Pennsylvania"],["RI","Rhode Island"],["SC","South Carolina"],["SD","South Dakota"],["TN","Tennessee"],["TX","Texas"],["UT","Utah"],["VT","Vermont"],["VA","Virginia"],["WA","Washington"],["WV","West Virginia"],["WI","Wisconsin"],["WY","Wyoming"],["DC","Washington, DC"]
] as const;

function normalizeLocationName(value:string){
return value.toLowerCase().replace(/[^a-z0-9]/g,"");
}

type Provider = { id:number; name:string|null; last_name:string|null; business_name:string|null; phone:string|null; email:string|null; city:string|null; state:string|null; zip_code?:string|null; bio:string|null; name_display?:string|null; user_id:string|null; contact_call?:boolean|null; contact_text?:boolean|null; contact_email?:boolean|null; contact_youlistify?:boolean|null; available_now?:boolean|null; service_mode?:string|null; customer_comes_to_me?:boolean|null; mobile_service?:boolean|null; pricing_methods:string[]|null; starting_price:number|null; flat_price:number|null; profile_photo?:string|null; gallery_photos?:string[]|null; };

export default function EditListingPage(){
const [providerId,setProviderId]=useState<number|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [selectedServiceIds,setSelectedServiceIds]=useState<number[]>([]); const [services,setServices]=useState<any[]>([]); const [serviceSearch,setServiceSearch]=useState(""); const [profilePhoto,setProfilePhoto]=useState(""); const [galleryPhotos,setGalleryPhotos]=useState<string[]>([]);
const [locationSuggestions,setLocationSuggestions]=useState<Array<{city:string;state:string}>>([]); const [cityOpen,setCityOpen]=useState(false); const [cityLoading,setCityLoading]=useState(false); const [zipChecking,setZipChecking]=useState(false); const [zipError,setZipError]=useState("");
const [form,setForm]=useState({name:"",last_name:"",business_name:"",phone:"",email:"",city:"",state:"",zip_code:"",bio:"",name_display:"full",contact_call:false,contact_text:false,contact_email:false,contact_youlistify:false,available_now:false,service_mode:"",customer_comes_to_me:false,mobile_service:false,pricing_methods:[] as string[],starting_price:"",flat_price:""});

useEffect(()=>{async function loadProvider(){
const {data:allServices,error:servicesError}=await supabase.from("services").select("id, name, category").order("category").order("name"); if(!servicesError&&allServices)setServices(allServices);
const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href="/sign-in";return;}
const {data,error}=await supabase.from("Providers").select("id,name,last_name,business_name,phone,email,city,state,zip_code,bio,name_display,user_id,contact_call,contact_text,contact_email,contact_youlistify,available_now,service_mode,customer_comes_to_me,mobile_service,pricing_methods,starting_price,flat_price,profile_photo,gallery_photos").eq("user_id",user.id).single();
if(error||!data){setMessage("We could not find your provider listing.");setLoading(false);return;}
const provider=data as Provider; setProviderId(provider.id); setProfilePhoto(provider.profile_photo??""); setGalleryPhotos(provider.gallery_photos??[]);
const {data:serviceLinks,error:serviceError}=await supabase.from("provider_services").select("service_id").eq("provider_id",provider.id); if(!serviceError&&serviceLinks)setSelectedServiceIds(serviceLinks.map((row:any)=>row.service_id));
const normalizedPricingMethods=(provider.pricing_methods||[]).map(method=>method==="hourly"?"Hourly rate":method==="flat"?"Flat rate":method==="contact"?"Contact for pricing":method);
setForm({name:provider.name||"",last_name:provider.last_name||"",business_name:provider.business_name||"",phone:provider.phone||"",email:provider.email||"",city:provider.city||"",state:provider.state||"",zip_code:provider.zip_code||"",bio:provider.bio||"",name_display:provider.name_display||"full",contact_call:provider.contact_call??false,contact_text:provider.contact_text??false,contact_email:provider.contact_email??false,contact_youlistify:provider.contact_youlistify??false,available_now:provider.available_now??false,service_mode:provider.service_mode||"",customer_comes_to_me:provider.customer_comes_to_me??false,mobile_service:provider.mobile_service??false,pricing_methods:normalizedPricingMethods,starting_price:provider.starting_price?.toString()||"",flat_price:provider.flat_price?.toString()||""}); setLoading(false); } void loadProvider();},[]);

useEffect(()=>{const query=form.city.trim();if(query.length<2){setLocationSuggestions([]);setCityLoading(false);return;}const controller=new AbortController();const timer=window.setTimeout(async()=>{setCityLoading(true);try{const response=await fetch(`/api/cities?q=${encodeURIComponent(query)}`,{signal:controller.signal});const data=await response.json();if(!controller.signal.aborted)setLocationSuggestions(Array.isArray(data.locations)?data.locations:[]);}catch{if(!controller.signal.aborted)setLocationSuggestions([]);}finally{if(!controller.signal.aborted)setCityLoading(false);}},180);return()=>{window.clearTimeout(timer);controller.abort();};},[form.city]);

async function validateZipLocation(){
const zip=form.zip_code.trim(); const city=form.city.trim(); const state=form.state.trim().toUpperCase();
if(!city||!state){setZipError("Please select a city and state before entering the ZIP code.");return false;}
if(!/^\d{5}$/.test(zip)){setZipError("Please enter a valid 5-digit ZIP code.");return false;}
setZipChecking(true); setZipError("");
try{const response=await fetch(`/api/cities?zip=${encodeURIComponent(zip)}`);const data=await response.json();if(!response.ok||data?.unavailable){setZipError("We could not verify that ZIP code right now. Please try again.");return false;}const locations=Array.isArray(data?.locations)?data.locations:[];const matches=locations.some((location:{city?:string;state?:string})=>normalizeLocationName(location.city||"")===normalizeLocationName(city)&&(location.state||"").toUpperCase()===state);if(!matches){setZipError(`That ZIP code does not match ${city}, ${state}.`);return false;}return true;}catch{setZipError("We could not verify that ZIP code right now. Please try again.");return false;}finally{setZipChecking(false);}
}

function updateField(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>){setForm({...form,[e.target.name]:e.target.value});}
async function handleSignOut(){await supabase.auth.signOut();window.location.href="/";}
async function uploadProfilePhoto(file:File|undefined){if(!file||!providerId)return;setMessage("");const fileExt=file.name.split(".").pop();const filePath=`${providerId}/profile-photo-${crypto.randomUUID()}.${fileExt}`;const {error}=await supabase.storage.from("provider-photos").upload(filePath,file);if(error){setMessage("Profile photo could not be uploaded: "+error.message);return;}const {data}=supabase.storage.from("provider-photos").getPublicUrl(filePath);const publicUrl=data.publicUrl;const {error:savePhotoError}=await supabase.from("Providers").update({profile_photo:publicUrl}).eq("id",providerId);if(savePhotoError){setMessage("Photo uploaded, but could not be saved to your listing: "+savePhotoError.message);return;}setProfilePhoto(publicUrl);setMessage("Profile photo updated.");}
async function uploadGalleryPhotos(files:FileList|null){if(!files||!providerId)return;const remaining=6-galleryPhotos.length;const filesToUpload=Array.from(files).slice(0,remaining);if(!filesToUpload.length){setMessage("You can add up to 6 photos.");return;}const newUrls:string[]=[];for(const file of filesToUpload){const fileExt=file.name.split(".").pop();const filePath=`${providerId}/${crypto.randomUUID()}.${fileExt}`;const {error}=await supabase.storage.from("provider-photos").upload(filePath,file);if(error){setMessage("One of the photos could not be uploaded.");continue;}const {data}=supabase.storage.from("provider-photos").getPublicUrl(filePath);newUrls.push(data.publicUrl);}setGalleryPhotos(current=>[...current,...newUrls]);}
async function saveListing(e:React.FormEvent){e.preventDefault();if(!providerId)return;if(!(await validateZipLocation())){setMessage("Please fix the city, state, or ZIP code above before saving.");return;}if(selectedServiceIds.length===0){alert("Please choose a service.");return;}if(!form.service_mode){alert("Please choose how you provide your service.");return;}if((form.service_mode==="local"||form.service_mode==="both")&&!form.customer_comes_to_me&&!form.mobile_service){setMessage("Please choose at least one Local service detail above before saving.");return;}if(!form.contact_call&&!form.contact_text&&!form.contact_email&&!form.contact_youlistify){alert("Please choose at least one way customers can contact you.");return;}if((form.contact_call||form.contact_text)&&!form.phone.trim()){alert("Please enter a phone number for Call or Text contact.");return;}if(form.contact_email&&!form.email.trim()){alert("Please enter an email address for Email contact.");return;}setSaving(true);setMessage("");const {error}=await supabase.from("Providers").update({name:form.name,last_name:form.last_name,business_name:form.business_name,phone:form.phone,email:form.email,city:form.city.trim(),state:form.state,zip_code:form.zip_code,bio:form.bio,name_display:form.name_display,contact_call:form.contact_call,contact_text:form.contact_text,contact_email:form.contact_email,contact_youlistify:form.contact_youlistify,available_now:form.available_now,service_mode:form.service_mode,customer_comes_to_me:form.customer_comes_to_me,mobile_service:form.mobile_service,pricing_methods:form.pricing_methods,starting_price:form.starting_price===""?null:Number(form.starting_price),flat_price:form.flat_price===""?null:Number(form.flat_price),profile_photo:profilePhoto||null,gallery_photos:galleryPhotos}).eq("id",providerId);if(error){setMessage("Could not save changes: "+error.message);setSaving(false);return;}const {error:deleteServicesError}=await supabase.from("provider_services").delete().eq("provider_id",providerId);if(deleteServicesError){setMessage("Could not update services: "+deleteServicesError.message);setSaving(false);return;}const {error:insertServicesError}=await supabase.from("provider_services").insert(selectedServiceIds.map(serviceId=>({provider_id:providerId,service_id:serviceId})));if(insertServicesError){setMessage("Could not update services: "+insertServicesError.message);setSaving(false);return;}setMessage("Your listing has been updated!");setSaving(false);}
if(loading)return <main style={{padding:"40px",fontFamily:"Arial, sans-serif"}}>Loading your listing...</main>;
const fieldStyle={padding:"14px",borderRadius:"10px",border:"1px solid #ddd"} as const;
return <main className="list-service-page" style={{maxWidth:"760px",margin:"70px auto",padding:"48px",background:"white",borderRadius:"24px",boxShadow:"0 12px 40px rgba(0,0,0,0.08)"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"10px",marginBottom:"24px"}}><a href="/dashboard" style={{display:"flex",alignItems:"center",justifyContent:"center",minHeight:"48px",padding:"10px 14px",border:"2px solid #d9dce7",borderRadius:"12px",background:"white",color:"#344054",fontWeight:"700",textDecoration:"none",textAlign:"center",boxSizing:"border-box"}}>← Back to Dashboard</a>{providerId&&<a href={`/provider/${providerId}`} style={{display:"flex",alignItems:"center",justifyContent:"center",minHeight:"48px",padding:"10px 14px",border:"2px solid #5b4cf0",borderRadius:"12px",background:"#5b4cf0",color:"white",fontWeight:"700",textDecoration:"none",textAlign:"center",boxSizing:"border-box"}}>View My Listing →</a>}</div><div style={{color:"#5b4cf0",fontWeight:"700",marginBottom:"12px"}}>MY YOULISTIFY LISTING</div><h1 style={{fontSize:"56px",lineHeight:"1",margin:"0 0 18px",color:"#182033"}}>Edit my listing</h1><p style={{fontSize:"18px",color:"#667085",marginBottom:"32px"}}>Update your YouListify provider profile and keep your information current.</p>
<form onSubmit={saveListing} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"16px"}}>
<input placeholder="First name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} style={fieldStyle}/><input placeholder="Last name" value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})} style={fieldStyle}/><input placeholder="Business name (optional)" value={form.business_name} onChange={e=>setForm({...form,business_name:e.target.value})} style={fieldStyle}/><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} style={fieldStyle}/><input placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} style={fieldStyle}/>
<div style={{gridColumn:"1 / -1",border:"1px solid #ddd6fe",background:"#faf9ff",borderRadius:"12px",padding:"18px"}}><div style={{fontWeight:"700",fontSize:"18px",marginBottom:"6px",color:"#182033"}}>How do you provide your service?</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"14px"}}>Choose the option that best describes how customers can work with you.</div><div style={{display:"grid",gap:"11px"}}>{[["local","Local / In person"],["remote","Remote / Online / Phone"],["both","Both local and remote"]].map(([value,label])=><label key={value} style={{display:"flex",alignItems:"center",gap:"10px",cursor:"pointer"}}><input type="radio" name="service_mode" checked={form.service_mode===value} onChange={()=>setForm({...form,service_mode:value})}/><strong>{label}</strong></label>)}</div></div>
<div style={{gridColumn:"1 / -1",marginBottom:"-6px"}}><div style={{fontWeight:"700",color:"#182033"}}>{form.service_mode==="remote"?"Your home location":"Your service location"}</div><div style={{fontSize:"14px",color:"#667085",marginTop:"5px",lineHeight:1.5}}>{form.service_mode==="remote"?"Enter where you are based. Your city will appear with your Remote / Online / Phone status.":"Enter your location so nearby customers can find you."}</div></div>
<div style={{position:"relative",width:"100%"}}><input placeholder="City" value={form.city} autoComplete="off" onFocus={()=>setCityOpen(true)} onChange={e=>{setForm({...form,city:e.target.value});setZipError("");setCityOpen(true);}} onBlur={()=>window.setTimeout(()=>setCityOpen(false),180)} style={{...fieldStyle,width:"100%",boxSizing:"border-box"}}/>{cityLoading&&form.city.trim().length>=2&&<div style={{fontSize:"13px",color:"#667085",marginTop:"6px"}}>Finding cities…</div>}{cityOpen&&locationSuggestions.length>0&&<div style={{position:"absolute",left:0,right:0,top:"calc(100% + 4px)",zIndex:100,background:"white",border:"1px solid #ddd",borderRadius:"10px",boxShadow:"0 10px 25px rgba(0,0,0,.12)",maxHeight:"240px",overflowY:"auto"}}>{locationSuggestions.map(location=><button key={`${location.city}-${location.state}`} type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>{setForm({...form,city:location.city,state:location.state||form.state});setZipError("");setCityOpen(false);}} style={{display:"block",width:"100%",padding:"12px 14px",border:0,borderBottom:"1px solid #eee",background:"white",textAlign:"left",cursor:"pointer",fontSize:"16px",color:"#182033"}}>{location.city}{location.state?`, ${location.state}`:""}</button>)}</div>}</div>
<select value={form.state} autoComplete="address-level1" onChange={e=>{setForm({...form,state:e.target.value});setZipError("");}} style={fieldStyle}><option value="">Select state</option>{STATES.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><div><input placeholder="ZIP code" value={form.zip_code} inputMode="numeric" maxLength={5} onChange={e=>{setForm({...form,zip_code:e.target.value.replace(/\D/g,"").slice(0,5)});setZipError("");}} onBlur={()=>{if(form.zip_code.trim())void validateZipLocation();}} aria-invalid={Boolean(zipError)} aria-describedby="zip-error" style={{...fieldStyle,width:"160px",maxWidth:"100%",borderColor:zipError?"#d92d20":"#ddd"}}/>{zipChecking&&<div style={{fontSize:"13px",color:"#667085",marginTop:"6px"}}>Checking ZIP code…</div>}{zipError&&<div id="zip-error" role="alert" style={{fontSize:"13px",color:"#d92d20",marginTop:"6px",lineHeight:1.35}}>{zipError}</div>}</div>
{(form.service_mode==="local"||form.service_mode==="both")&&<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"6px"}}>Local service details</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Select all that apply.</div><div style={{display:"grid",gap:"12px"}}><label style={{display:"flex",alignItems:"center",gap:"10px",cursor:"pointer"}}><input type="checkbox" checked={form.customer_comes_to_me} onChange={e=>setForm({...form,customer_comes_to_me:e.target.checked})}/><strong>Customer comes to me / my location</strong></label><label style={{display:"flex",alignItems:"center",gap:"10px",cursor:"pointer"}}><input type="checkbox" checked={form.mobile_service} onChange={e=>setForm({...form,mobile_service:e.target.checked})}/><strong>Mobile / I travel to customers</strong></label></div></div>}
<div style={{display:"grid",gap:"10px",gridColumn:"1 / -1"}}><div style={{fontWeight:"600"}}>What services do you offer? Select all that apply.</div><input type="text" placeholder="Search services..." value={serviceSearch} onChange={e=>setServiceSearch(e.target.value)} style={{padding:"12px",borderRadius:"10px",border:"1px solid #ddd",width:"100%"}}/>{services.filter((service:any)=>{if(selectedServiceIds.includes(Number(service.id)))return true;const q=serviceSearch.trim().toLowerCase();if(!q)return false;const name=service.name.toLowerCase();return q.length===1?name.startsWith(q):name.includes(q);}).sort((a:any,b:any)=>{const q=serviceSearch.trim().toLowerCase();const aName=a.name.toLowerCase();const bName=b.name.toLowerCase();const aRank=aName===q?0:aName.startsWith(q)?1:aName.split(/\s+/).some((word:string)=>word.startsWith(q))?2:3;const bRank=bName===q?0:bName.startsWith(q)?1:bName.split(/\s+/).some((word:string)=>word.startsWith(q))?2:3;return aRank-bRank||aName.localeCompare(bName);}).slice(0,12).map((service:any)=><label key={service.id} style={{display:"flex",alignItems:"center",gap:"10px",padding:"10px",border:"1px solid #ddd",borderRadius:"10px",cursor:"pointer"}}><input type="checkbox" checked={selectedServiceIds.includes(Number(service.id))} onChange={e=>{const serviceId=Number(service.id);setSelectedServiceIds(e.target.checked?[...selectedServiceIds,serviceId]:selectedServiceIds.filter(id=>id!==serviceId));}}/>{service.name}</label>)}</div>
<div style={{gridColumn:"1 / -1"}}><div style={{fontWeight:"600",marginBottom:"6px"}}>About your services</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Tell customers what you do, your experience, and what makes your service stand out.</div><textarea placeholder="Describe your services..." value={form.bio} maxLength={750} onChange={e=>setForm({...form,bio:e.target.value})} style={{width:"100%",padding:"14px",borderRadius:"10px",border:"1px solid #ddd",minHeight:"150px",resize:"vertical",fontSize:"16px"}}/></div>
<div style={{gridColumn:"1 / -1"}}><div style={{fontWeight:"600",marginBottom:"6px"}}>How do you charge?</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Select all that apply. You can add rates if you'd like, but pricing is optional.</div>{["Hourly rate","Flat rate","Contact for pricing"].map(method=><label key={method} style={{display:"flex",alignItems:"center",gap:"10px",padding:"8px 0",cursor:"pointer"}}><input type="checkbox" checked={form.pricing_methods.includes(method)} onChange={e=>setForm({...form,pricing_methods:e.target.checked?[...form.pricing_methods,method]:form.pricing_methods.filter(m=>m!==method)})}/>{method}</label>)}{form.pricing_methods.includes("Hourly rate")&&<div style={{marginTop:"12px"}}><div style={{fontSize:"14px",marginBottom:"6px"}}>Hourly rate (optional)</div><input placeholder="Example: 75" value={form.starting_price} onChange={e=>setForm({...form,starting_price:e.target.value})} style={{padding:"12px",borderRadius:"10px",border:"1px solid #ddd",width:"180px"}}/></div>}{form.pricing_methods.includes("Flat rate")&&<div style={{marginTop:"12px"}}><div style={{fontSize:"14px",marginBottom:"6px"}}>Flat rate (optional)</div><input placeholder="Example: 250" value={form.flat_price} onChange={e=>setForm({...form,flat_price:e.target.value})} style={{padding:"12px",borderRadius:"10px",border:"1px solid #ddd",width:"180px"}}/></div>}</div>
<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"6px"}}>How can customers contact you?</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Select all the contact options you want displayed on your public listing.</div>{[["contact_call","Call"],["contact_text","Text"],["contact_email","Email"],["contact_youlistify","Contact through YouListify"]].map(([field,label])=><label key={field} style={{display:"flex",alignItems:"center",gap:"10px",padding:"8px 0",cursor:"pointer"}}><input type="checkbox" checked={Boolean(form[field as keyof typeof form])} onChange={e=>setForm({...form,[field]:e.target.checked})}/>{label}</label>)}</div>
<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"6px"}}>How would you like your name displayed?</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Choose how your name will appear to customers on your public listing.</div><label style={{display:"block",padding:"7px 0"}}><input type="radio" name="name_display" checked={form.name_display==="full"} onChange={()=>setForm({...form,name_display:"full"})}/> Full Name</label><label style={{display:"block",padding:"7px 0"}}><input type="radio" name="name_display" checked={form.name_display==="initial"} onChange={()=>setForm({...form,name_display:"initial"})}/> First Name + Last Initial</label><label style={{display:"block",padding:"7px 0"}}><input type="radio" name="name_display" checked={form.name_display==="first"} onChange={()=>setForm({...form,name_display:"first"})}/> First Name Only</label></div>
<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"10px"}}>Availability</div><label style={{display:"block",marginBottom:"10px"}}><input type="radio" name="availability" checked={form.available_now} onChange={()=>setForm({...form,available_now:true})}/> Available now</label><label style={{display:"block"}}><input type="radio" name="availability" checked={!form.available_now} onChange={()=>setForm({...form,available_now:false})}/> Not available now</label></div>
<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"6px"}}>Profile photo</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"12px"}}>This is the main photo customers will see on your public listing.</div>{profilePhoto&&<img src={profilePhoto} alt="Profile" style={{width:"110px",height:"110px",objectFit:"cover",borderRadius:"24px",display:"block",marginBottom:"12px"}}/>}<input type="file" accept="image/*" onChange={e=>uploadProfilePhoto(e.target.files?.[0])}/></div>
<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"6px"}}>Gallery photos</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"12px"}}>Add up to 6 photos of your work, services, or business.</div><input type="file" accept="image/*" multiple onChange={e=>uploadGalleryPhotos(e.target.files)}/><div style={{display:"grid",gridTemplateColumns:"repeat(3, 1fr)",gap:"10px",marginTop:"16px"}}>{galleryPhotos.map((photo,index)=><img key={index} src={photo} alt={`Gallery photo ${index+1}`} style={{width:"100%",height:"120px",objectFit:"cover",borderRadius:"10px"}}/>)}</div></div>
{message&&<p style={{gridColumn:"1 / -1",marginTop:"2px",color:"#4f46e5",fontWeight:"600"}}>{message}</p>}<button type="submit" disabled={saving} style={{gridColumn:"1 / -1",padding:"16px",border:"none",borderRadius:"12px",background:"#5b4cf0",color:"white",fontWeight:"700",fontSize:"16px",cursor:"pointer",marginTop:"8px"}}>{saving?"Saving...":"Save Listing"}</button>{providerId&&<a href={`/provider/${providerId}`} style={{gridColumn:"1 / -1",display:"block",width:"100%",padding:"14px",border:"2px solid #4f46e5",borderRadius:"12px",background:"white",color:"#4f46e5",fontWeight:"700",fontSize:"16px",textAlign:"center",textDecoration:"none",boxSizing:"border-box"}}>View My Listing →</a>}<a href="/dashboard" style={{gridColumn:"1 / -1",display:"block",width:"100%",padding:"14px",border:"2px solid #e5e7eb",borderRadius:"12px",background:"#f8f8fb",color:"#344054",fontWeight:"700",fontSize:"16px",textAlign:"center",textDecoration:"none",boxSizing:"border-box"}}>← Back to Dashboard</a><button className="edit-sign-out" type="button" onClick={handleSignOut} style={{gridColumn:"1 / -1",justifySelf:"end",width:"auto",padding:"8px 4px",border:0,background:"transparent",color:"#667085",fontWeight:"600",fontSize:"15px",textDecoration:"underline",cursor:"pointer"}}>Sign out</button></form></main>;
}
