"use client";

import "./mobile.css";
import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

const STATES = [
["AL","Alabama"],["AK","Alaska"],["AZ","Arizona"],["AR","Arkansas"],["CA","California"],["CO","Colorado"],["CT","Connecticut"],["DE","Delaware"],["FL","Florida"],["GA","Georgia"],["HI","Hawaii"],["ID","Idaho"],["IL","Illinois"],["IN","Indiana"],["IA","Iowa"],["KS","Kansas"],["KY","Kentucky"],["LA","Louisiana"],["ME","Maine"],["MD","Maryland"],["MA","Massachusetts"],["MI","Michigan"],["MN","Minnesota"],["MS","Mississippi"],["MO","Missouri"],["MT","Montana"],["NE","Nebraska"],["NV","Nevada"],["NH","New Hampshire"],["NJ","New Jersey"],["NM","New Mexico"],["NY","New York"],["NC","North Carolina"],["ND","North Dakota"],["OH","Ohio"],["OK","Oklahoma"],["OR","Oregon"],["PA","Pennsylvania"],["RI","Rhode Island"],["SC","South Carolina"],["SD","South Dakota"],["TN","Tennessee"],["TX","Texas"],["UT","Utah"],["VT","Vermont"],["VA","Virginia"],["WA","Washington"],["WV","West Virginia"],["WI","Wisconsin"],["WY","Wyoming"],["DC","Washington, DC"]
] as const;

const fieldStyle={padding:"14px",borderRadius:"10px",border:"1px solid #ddd"} as const;

function normalizeLocationName(value:string){
return value.toLowerCase().replace(/[^a-z0-9]/g,"");
}

export default function ListService(){
const [services,setServices]=useState<any[]>([]);
const [serviceSearch,setSearch]=useState("");
const [submitted,setSubmitted]=useState(false);
const [password,setPassword]=useState("");
const [showAccountForm,setShowAccountForm]=useState(false);
const [accountCreated,setAccountCreated]=useState(false);
const [createdProviderId,setCreatedProviderId]=useState<number|null>(null);
const [acceptedLegalTerms,setAcceptedLegalTerms]=useState(false);
const [signedInUserId,setSignedInUserId]=useState("");
const [locationSuggestions,setLocationSuggestions]=useState<Array<{city:string;state:string}>>([]);
const [cityOpen,setCityOpen]=useState(false);
const [cityLoading,setCityLoading]=useState(false);
const [zipChecking,setZipChecking]=useState(false);
const [zipError,setZipError]=useState("");
const [form,setForm]=useState({name:"",last_name:"",business_name:"",phone:"",email:"",contact_call:false,contact_text:false,contact_email:false,contact_youlistify:false,available_now:false,service_mode:"",display_city:true,customer_comes_to_me:false,mobile_service:false,city:"",state:"",zip_code:"",bio:"",pricing_methods:[] as string[],starting_price:"",flat_price:"",service_ids:[] as number[],name_display:"full"});

useEffect(()=>{async function loadServices(){const {data,error}=await supabase.from("services").select("id, name, category").order("category").order("name");if(!error&&data)setServices(data);}void loadServices();},[]);
useEffect(()=>{async function loadSignedInUser(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;setSignedInUserId(user.id);setForm(current=>({...current,email:current.email||user.email||""}));}void loadSignedInUser();},[]);
useEffect(()=>{const query=form.city.trim();if(query.length<2){setLocationSuggestions([]);setCityLoading(false);return;}const controller=new AbortController();const timer=window.setTimeout(async()=>{setCityLoading(true);try{const response=await fetch(`/api/cities?q=${encodeURIComponent(query)}`,{signal:controller.signal});const data=await response.json();if(!controller.signal.aborted)setLocationSuggestions(Array.isArray(data.locations)?data.locations:[]);}catch{if(!controller.signal.aborted)setLocationSuggestions([]);}finally{if(!controller.signal.aborted)setCityLoading(false);}},180);return()=>{window.clearTimeout(timer);controller.abort();};},[form.city]);

async function validateZipLocation(){
const zip=form.zip_code.trim();
const city=form.city.trim();
const state=form.state.trim().toUpperCase();
if(!city||!state){setZipError("Please select a city and state before entering the ZIP code.");return false;}
if(!/^\\d{5}$/.test(zip)){setZipError("Please enter a valid 5-digit ZIP code.");return false;}
setZipChecking(true);
setZipError("");
try{
const response=await fetch(`/api/cities?zip=${encodeURIComponent(zip)}`);
const data=await response.json();
if(!response.ok||data?.unavailable){setZipError("We could not verify that ZIP code right now. Please try again.");return false;}
const locations=Array.isArray(data?.locations)?data.locations:[];
const matches=locations.some((location:{city?:string;state?:string})=>normalizeLocationName(location.city||"")===normalizeLocationName(city)&&(location.state||"").toUpperCase()===state);
if(!matches){setZipError(`That ZIP code does not match ${city}, ${state}.`);return false;}
return true;
}catch{
setZipError("We could not verify that ZIP code right now. Please try again.");
return false;
}finally{setZipChecking(false);}
}

async function createAccount(){if(!form.email||!password){alert("Please enter a password.");return;}if(!acceptedLegalTerms){alert("Please agree to the Terms of Use and acknowledge the Privacy Policy to create your account.");return;}const {error}=await supabase.auth.signUp({email:form.email,password});if(error){alert("Could not create account: "+error.message);return;}setAccountCreated(true);}

async function saveProvider(e:React.FormEvent){e.preventDefault();if(!(await validateZipLocation()))return;if(form.service_ids.length===0){alert("Please choose a service.");return;}if(!form.service_mode){alert("Please choose how you provide your service.");return;}if(!form.contact_call&&!form.contact_text&&!form.contact_email&&!form.contact_youlistify){alert("Please choose at least one way customers can contact you.");return;}if((form.contact_call||form.contact_text)&&!form.phone.trim()){alert("Please enter a phone number for Call or Text contact.");return;}if(form.contact_email&&!form.email.trim()){alert("Please enter an email address for Email contact.");return;}const {service_ids,...rest}=form;const providerData={...rest,user_id:signedInUserId||null,city:form.city.trim(),starting_price:form.starting_price===""?null:Number(form.starting_price),flat_price:form.flat_price===""?null:Number(form.flat_price)};const {data:newProvider,error:providerError}=await supabase.from("Providers").insert([providerData]).select("id").single();if(providerError){alert("Something went wrong: "+providerError.message);return;}const {error:serviceError}=await supabase.from("provider_services").insert(service_ids.map(serviceId=>({provider_id:newProvider.id,service_id:serviceId})));if(serviceError){alert("Provider saved, but service could not be added: "+serviceError.message);return;}setCreatedProviderId(Number(newProvider.id));setSubmitted(true);}

if(accountCreated)return <main className="list-service-page listing-success" style={{maxWidth:"760px",margin:"70px auto",padding:"48px",background:"white",borderRadius:"24px",boxShadow:"0 12px 40px rgba(0,0,0,0.08)",textAlign:"center"}}><div style={{fontSize:"56px",marginBottom:"16px"}}>🎉</div><h1 style={{fontSize:"42px",marginBottom:"16px",color:"#182033"}}>Your account has been created!</h1><p style={{fontSize:"18px",color:"#667085",lineHeight:"1.6"}}>Please check your email and confirm your YouListify account.</p><p style={{fontSize:"18px",color:"#667085",lineHeight:"1.6"}}>After confirming, sign in to open your dashboard, edit your listing, add photos, and keep your information current.</p><div className="success-actions"><a href="/sign-in" className="success-primary">Confirm Email, Then Sign In</a>{createdProviderId&&<a href={`/provider/${createdProviderId}`} className="success-secondary">View My Listing</a>}<a href="/" className="success-secondary">← Back to YouListify</a></div></main>;
if(submitted&&!showAccountForm)return <main className="list-service-page listing-success" style={{maxWidth:"760px",margin:"70px auto",padding:"48px",background:"white",borderRadius:"24px",boxShadow:"0 12px 40px rgba(0,0,0,0.08)",textAlign:"center"}}><div style={{fontSize:"56px",marginBottom:"16px"}}>🎉</div><h1 style={{fontSize:"42px",marginBottom:"16px",color:"#182033"}}>Your listing has been created!</h1><p style={{fontSize:"18px",color:"#667085",lineHeight:"1.6"}}>Welcome to YouListify! Your service listing is now saved.</p>{signedInUserId?<><p style={{fontSize:"18px",color:"#667085",lineHeight:"1.6"}}>Your listing was added to your existing YouListify account.</p><div className="success-actions"><a href="/dashboard" className="success-primary">Go to Dashboard</a><a href="/" className="success-secondary">← Back to YouListify</a></div></>:<><p style={{fontSize:"18px",color:"#667085",lineHeight:"1.6"}}>Create your free provider account to manage your listing, make updates, add photos, and keep your information current.</p><button type="button" onClick={()=>setShowAccountForm(true)} style={{width:"100%",padding:"16px",marginTop:"20px",border:"none",borderRadius:"12px",background:"#5b4cf0",color:"white",fontWeight:"700",fontSize:"16px",cursor:"pointer"}}>Create My Account</button><a href="/" className="success-secondary">← Back to YouListify</a></>}</main>;
if(showAccountForm)return <main className="list-service-page" style={{maxWidth:"760px",margin:"70px auto",padding:"48px",background:"white",borderRadius:"24px",boxShadow:"0 12px 40px rgba(0,0,0,0.08)"}}><h1 style={{fontSize:"42px",marginBottom:"12px",color:"#182033"}}>Create your account</h1><p style={{fontSize:"18px",color:"#667085",lineHeight:"1.6",marginBottom:"28px"}}>You're almost done! Create your free provider account to manage your listing, add photos, and make updates anytime.</p><input type="email" value={form.email} readOnly style={{width:"100%",padding:"14px",borderRadius:"10px",border:"1px solid #ddd",marginBottom:"14px"}}/><input type="password" placeholder="Create a password" value={password} onChange={e=>setPassword(e.target.value)} style={{width:"100%",padding:"14px",borderRadius:"10px",border:"1px solid #ddd",marginBottom:"18px"}}/><label style={{display:"flex",alignItems:"flex-start",gap:"10px",margin:"0 0 18px",color:"#475467",fontSize:"14px",lineHeight:1.5,cursor:"pointer"}}><input type="checkbox" checked={acceptedLegalTerms} onChange={e=>setAcceptedLegalTerms(e.target.checked)} style={{marginTop:"3px",width:"18px",height:"18px",flex:"0 0 auto"}}/><span>I agree to YouListify&apos;s <a href="/terms?from=create-listing" target="_blank" rel="noopener noreferrer" style={{color:"#5b4cf0",fontWeight:700}}>Terms of Use</a> and acknowledge the <a href="/privacy?from=create-listing" target="_blank" rel="noopener noreferrer" style={{color:"#5b4cf0",fontWeight:700}}>Privacy Policy</a>.</span></label><button type="button" onClick={createAccount} style={{width:"100%",padding:"16px",border:"none",borderRadius:"12px",background:"#5b4cf0",color:"white",fontWeight:"700",fontSize:"16px",cursor:"pointer"}}>Create My Account</button></main>;

return <main className="list-service-page" style={{maxWidth:"760px",margin:"70px auto",padding:"48px",background:"white",borderRadius:"24px",boxShadow:"0 12px 40px rgba(0,0,0,0.08)"}}><a href="/" style={{display:"inline-block",color:"#5b4cf0",fontWeight:"700",textDecoration:"none",marginBottom:"18px"}}>← Back to YouListify</a><div style={{color:"#5b4cf0",fontWeight:"700",marginBottom:"12px"}}>JOIN YOULISTIFY</div><h1 style={{fontSize:"56px",lineHeight:"1",margin:"0 0 18px",color:"#182033"}}>List your service</h1><p style={{fontSize:"18px",color:"#667085",marginBottom:"32px"}}>Create your YouListify provider profile and start connecting with customers.</p>
<form onSubmit={saveProvider} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"16px"}}>
<input placeholder="First name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} style={fieldStyle}/><input placeholder="Last name" value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})} style={fieldStyle}/><input placeholder="Business name (optional)" value={form.business_name} onChange={e=>setForm({...form,business_name:e.target.value})} style={fieldStyle}/><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} style={fieldStyle}/><input placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} style={fieldStyle}/>
<div style={{gridColumn:"1 / -1",border:"1px solid #ddd6fe",background:"#faf9ff",borderRadius:"12px",padding:"18px"}}><div style={{fontWeight:"700",fontSize:"18px",marginBottom:"6px",color:"#182033"}}>How do you provide your service?</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"14px"}}>Choose the option that best describes how customers can work with you.</div><div style={{display:"grid",gap:"11px"}}>{[["local","Local / In person"],["remote","Remote / Online / Phone"],["both","Both local and remote"]].map(([value,label])=><label key={value} style={{display:"flex",alignItems:"center",gap:"10px",cursor:"pointer"}}><input type="radio" name="service_mode" checked={form.service_mode===value} onChange={()=>setForm({...form,service_mode:value,display_city:value==="remote"?false:true})}/><strong>{label}</strong></label>)}</div></div>
<div style={{gridColumn:"1 / -1",marginBottom:"-6px"}}><div style={{fontWeight:"700",color:"#182033"}}>{form.service_mode==="remote"?"Your home location":"Your service location"}</div><div style={{fontSize:"14px",color:"#667085",marginTop:"5px",lineHeight:1.5}}>{form.service_mode==="remote"?"Enter your home location for account and search purposes. Your city will stay private unless you choose to display it.":"Enter your location so nearby customers can find you."}</div></div>
<div style={{position:"relative",width:"100%"}}><input placeholder="City" value={form.city} autoComplete="off" onFocus={()=>setCityOpen(true)} onChange={e=>{setForm({...form,city:e.target.value});setZipError("");setCityOpen(true);}} onBlur={()=>window.setTimeout(()=>setCityOpen(false),180)} style={{...fieldStyle,width:"100%",boxSizing:"border-box"}}/>{cityLoading&&form.city.trim().length>=2&&<div style={{fontSize:"13px",color:"#667085",marginTop:"6px"}}>Finding cities…</div>}{cityOpen&&locationSuggestions.length>0&&<div style={{position:"absolute",left:0,right:0,top:"calc(100% + 4px)",zIndex:100,background:"white",border:"1px solid #ddd",borderRadius:"10px",boxShadow:"0 10px 25px rgba(0,0,0,.12)",maxHeight:"240px",overflowY:"auto"}}>{locationSuggestions.map(location=><button key={`${location.city}-${location.state}`} type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>{setForm({...form,city:location.city,state:location.state||form.state});setZipError("");setCityOpen(false);}} style={{display:"block",width:"100%",padding:"12px 14px",border:0,borderBottom:"1px solid #eee",background:"white",textAlign:"left",cursor:"pointer",fontSize:"16px",color:"#182033"}}>{location.city}{location.state?`, ${location.state}`:""}</button>)}</div>}</div>
<select value={form.state} autoComplete="address-level1" onChange={e=>{setForm({...form,state:e.target.value});setZipError("");}} style={fieldStyle}><option value="">Select state</option>{STATES.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><div><input placeholder="ZIP code" value={form.zip_code} inputMode="numeric" maxLength={5} onChange={e=>{setForm({...form,zip_code:e.target.value.replace(/\\D/g,"").slice(0,5)});setZipError("");}} onBlur={()=>{if(form.zip_code.trim())void validateZipLocation();}} aria-invalid={Boolean(zipError)} aria-describedby="zip-error" style={{...fieldStyle,width:"160px",maxWidth:"100%",borderColor:zipError?"#d92d20":"#ddd"}}/>{zipChecking&&<div style={{fontSize:"13px",color:"#667085",marginTop:"6px"}}>Checking ZIP code…</div>}{zipError&&<div id="zip-error" role="alert" style={{fontSize:"13px",color:"#d92d20",marginTop:"6px",lineHeight:1.35}}>{zipError}</div>}</div>
{form.service_mode==="remote"&&<label style={{gridColumn:"1 / -1",display:"flex",alignItems:"center",gap:"10px",padding:"12px 14px",border:"1px solid #e5e7eb",borderRadius:"10px",cursor:"pointer"}}><input type="checkbox" checked={form.display_city} onChange={e=>setForm({...form,display_city:e.target.checked})}/><span><strong>Display my city on my public listing</strong><span style={{display:"block",fontSize:"13px",color:"#667085",marginTop:"3px"}}>Leave this unchecked to keep your city private.</span></span></label>}
<div style={{display:"grid",gap:"10px",gridColumn:"1 / -1"}}><div style={{fontWeight:"600"}}>What services do you offer? Select all that apply.</div><input type="text" placeholder="Search services..." value={serviceSearch} onChange={e=>setSearch(e.target.value)} style={{padding:"12px",borderRadius:"10px",border:"1px solid #ddd",width:"100%"}}/>{services.filter((service:any)=>{if(form.service_ids.includes(Number(service.id)))return true;const q=serviceSearch.trim().toLowerCase();if(!q)return false;const name=service.name.toLowerCase();return q.length===1?name.startsWith(q):name.includes(q);}).sort((a:any,b:any)=>{const q=serviceSearch.trim().toLowerCase();const aName=a.name.toLowerCase();const bName=b.name.toLowerCase();const aRank=aName===q?0:aName.startsWith(q)?1:aName.split(/\s+/).some((word:string)=>word.startsWith(q))?2:3;const bRank=bName===q?0:bName.startsWith(q)?1:bName.split(/\s+/).some((word:string)=>word.startsWith(q))?2:3;return aRank-bRank||aName.localeCompare(bName);}).slice(0,12).map((service:any)=><label key={service.id} style={{display:"flex",alignItems:"center",gap:"10px",padding:"10px",border:"1px solid #ddd",borderRadius:"10px",cursor:"pointer"}}><input type="checkbox" checked={form.service_ids.includes(Number(service.id))} onChange={e=>{const serviceId=Number(service.id);setForm({...form,service_ids:e.target.checked?[...form.service_ids,serviceId]:form.service_ids.filter(id=>id!==serviceId)});}}/>{service.name}</label>)}</div>
{(form.service_mode==="local"||form.service_mode==="both")&&<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"6px"}}>Local service details</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Select all that apply.</div><div style={{display:"grid",gap:"12px"}}><label style={{display:"flex",alignItems:"center",gap:"10px",cursor:"pointer"}}><input type="checkbox" checked={form.customer_comes_to_me} onChange={e=>setForm({...form,customer_comes_to_me:e.target.checked})}/><strong>Customer comes to me / my location</strong></label><label style={{display:"flex",alignItems:"center",gap:"10px",cursor:"pointer"}}><input type="checkbox" checked={form.mobile_service} onChange={e=>setForm({...form,mobile_service:e.target.checked})}/><strong>Mobile / I travel to customers</strong></label></div></div>}
<div style={{gridColumn:"1 / -1"}}><div style={{fontWeight:"600",marginBottom:"6px"}}>About your services</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Tell customers what you do, your experience, and what makes your service stand out.</div><textarea placeholder="Describe your services..." value={form.bio} maxLength={750} onChange={e=>setForm({...form,bio:e.target.value})} style={{width:"100%",padding:"14px",borderRadius:"10px",border:"1px solid #ddd",minHeight:"150px",resize:"vertical"}}/></div>
<div style={{gridColumn:"1 / -1"}}><div style={{fontWeight:"600",marginBottom:"6px"}}>How do you charge?</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Select all that apply. You can add rates if you'd like, but pricing is optional.</div>{["Hourly rate","Flat rate","Contact for pricing"].map(method=><label key={method} style={{display:"flex",alignItems:"center",gap:"10px",padding:"8px 0",cursor:"pointer"}}><input type="checkbox" checked={form.pricing_methods.includes(method)} onChange={e=>setForm({...form,pricing_methods:e.target.checked?[...form.pricing_methods,method]:form.pricing_methods.filter(m=>m!==method)})}/>{method}</label>)}{form.pricing_methods.includes("Hourly rate")&&<div style={{marginTop:"12px"}}><div style={{fontSize:"14px",marginBottom:"6px"}}>Hourly rate (optional)</div><input placeholder="Example: 75" value={form.starting_price} onChange={e=>setForm({...form,starting_price:e.target.value})} style={{padding:"12px",borderRadius:"10px",border:"1px solid #ddd",width:"180px"}}/></div>}{form.pricing_methods.includes("Flat rate")&&<div style={{marginTop:"12px"}}><div style={{fontSize:"14px",marginBottom:"6px"}}>Flat rate (optional)</div><input placeholder="Example: 250" value={form.flat_price} onChange={e=>setForm({...form,flat_price:e.target.value})} style={{padding:"12px",borderRadius:"10px",border:"1px solid #ddd",width:"180px"}}/></div>}</div>
<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"6px"}}>How can customers contact you?</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Select all the contact options you want displayed on your public listing.</div>{[["contact_call","Call"],["contact_text","Text"],["contact_email","Email"],["contact_youlistify","Contact through YouListify"]].map(([field,label])=><label key={field} style={{display:"flex",alignItems:"center",gap:"10px",padding:"8px 0",cursor:"pointer"}}><input type="checkbox" checked={Boolean(form[field as keyof typeof form])} onChange={e=>setForm({...form,[field]:e.target.checked})}/>{label}</label>)}</div>
<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"6px"}}>How would you like your name displayed?</div><div style={{fontSize:"14px",color:"#667085",marginBottom:"10px"}}>Choose how your name will appear to customers on your public listing.</div><label style={{display:"block",padding:"7px 0"}}><input type="radio" name="name_display" checked={form.name_display==="full"} onChange={()=>setForm({...form,name_display:"full"})}/> Full Name</label><label style={{display:"block",padding:"7px 0"}}><input type="radio" name="name_display" checked={form.name_display==="initial"} onChange={()=>setForm({...form,name_display:"initial"})}/> First Name + Last Initial</label><label style={{display:"block",padding:"7px 0"}}><input type="radio" name="name_display" checked={form.name_display==="first"} onChange={()=>setForm({...form,name_display:"first"})}/> First Name Only</label></div>
<div style={{gridColumn:"1 / -1",border:"1px solid #e5e7eb",borderRadius:"12px",padding:"16px"}}><div style={{fontWeight:"700",marginBottom:"10px"}}>Availability</div><label style={{display:"block",marginBottom:"10px"}}><input type="radio" name="availability" checked={form.available_now} onChange={()=>setForm({...form,available_now:true})}/> Available now</label><label style={{display:"block"}}><input type="radio" name="availability" checked={!form.available_now} onChange={()=>setForm({...form,available_now:false})}/> Not available now</label></div>
<button type="submit" style={{gridColumn:"1 / -1",padding:"16px",border:"none",borderRadius:"12px",background:"#5b4cf0",color:"white",fontWeight:"700",fontSize:"16px",cursor:"pointer",marginTop:"8px"}}>Create my listing</button></form></main>;
}
