create table if not exists public.work_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_type text not null check (post_type in ('job','gig','task')),
  title text not null,
  description text not null,
  category text,
  city text,
  state text,
  zip_code text,
  remote boolean not null default false,
  pay_type text not null default 'contact' check (pay_type in ('hourly','flat','salary','contact')),
  pay_amount numeric,
  contact_call boolean not null default false,
  contact_text boolean not null default false,
  contact_email boolean not null default true,
  contact_youlistify boolean not null default true,
  contact_phone text,
  contact_email_address text,
  application_url text,
  status text not null default 'active' check (status in ('active','paused','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.work_posts enable row level security;

drop policy if exists "Public can read active work posts" on public.work_posts;
create policy "Public can read active work posts"
on public.work_posts
for select
to public
using (status = 'active' or auth.uid() = user_id);

drop policy if exists "Authenticated users can create own work posts" on public.work_posts;
create policy "Authenticated users can create own work posts"
on public.work_posts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own work posts" on public.work_posts;
create policy "Users can update own work posts"
on public.work_posts
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own work posts" on public.work_posts;
create policy "Users can delete own work posts"
on public.work_posts
for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists work_posts_status_created_idx on public.work_posts (status, created_at desc);
create index if not exists work_posts_location_idx on public.work_posts (state, city);
create index if not exists work_posts_type_idx on public.work_posts (post_type);
