create table if not exists public.work_post_messages (
  id bigint generated by default as identity primary key,
  work_post_id bigint not null references public.work_posts(id) on delete cascade,
  sender_name text not null,
  sender_email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.work_post_messages enable row level security;

drop policy if exists "Anyone can send work post messages" on public.work_post_messages;
create policy "Anyone can send work post messages"
on public.work_post_messages
for insert
to anon, authenticated
with check (
  exists (
    select 1
    from public.work_posts wp
    where wp.id = work_post_id
      and wp.status = 'active'
      and wp.contact_youlistify = true
  )
);

drop policy if exists "Owners can read work post messages" on public.work_post_messages;
create policy "Owners can read work post messages"
on public.work_post_messages
for select
to authenticated
using (
  exists (
    select 1
    from public.work_posts wp
    where wp.id = work_post_id
      and wp.user_id = auth.uid()
  )
);

grant insert on table public.work_post_messages to anon, authenticated;
grant select on table public.work_post_messages to authenticated;
grant usage, select on sequence public.work_post_messages_id_seq to anon, authenticated;

create index if not exists work_post_messages_post_created_idx
on public.work_post_messages (work_post_id, created_at desc);
